### ISSUE TITLE
Implement Shipment Total Check in Brokering Service for Order Shipgroups

### ISSUE THREAD

**Issue by dixitdeepak** [hotwax/OrderRouting#4]
Enhance the Brokering Service to introduce a new check that evaluates the shipment total of order shipgroups against a predefined limit set at the product store level. This feature aims to conditionally broker or split order shipgroups based on their shipment totals, enhancing the order fulfillment process's flexibility and efficiency.

**Brokering Service Enhancement:**
Modify the Brokering Service to introduce logic that checks the shipment total of an order shipgroup against the configured limit.The shipment total limit check should only apply under specific conditions to maintain flexibility in order brokering and fulfillment.

**Condition Handling:**
**Full Brokerage on Single Location**: If an order shipgroup is fully brokered to a single location, bypass the shipment total check, allowing the shipgroup to proceed without splitting regardless of its total.
**Splitting Shipgroups:** Initiate the shipment total check only if there's an attempt to split the order shipgroup among multiple locations. This includes:
 - Evaluating each potential split or brokered location's item total against the allowed shipment total.
 - Proceeding with splitting the shipgroup only if all brokered locations' item totals are greater than or equal to the allowed shipment total.

**Condition Failure Handling:** If any one of the shipgroup items, when evaluated for splitting, does not meet the shipment total condition, do not broker or split the order shipgroup. Ensure the order processing logic can gracefully handle this scenario and provide appropriate feedback/logic for next steps (e.g., manual intervention, alternative brokering strategy).

**Comment by dt2patel** [comment]
https://docs.google.com/document/d/1SoQfc5wF5_Fu-9GIgawwbReW7I5qQ-iwK5qfgVG7Tro/edit#heading=h.2vxkom3q2egg

Linking related document. This is going to be needed soon in prod. Can we prioritize this?

**Comment by dixitdeepak** [comment]
Added following data for shipment threhold check:
`    <moqui.basic.Enumeration enumId="IFP_SHIP_THREHOLD" description="Shipment threshold check" sequenceNum="8" enumTypeId="INV_FILTER_PRM_TYPE" enumCode="shipmentThreshold"/>`
