### ISSUE TITLE
Select orders for brokering by product

### ISSUE THREAD

**Issue by dt2patel** [hotwax/OrderRouting#5]
Often times products are used as the condition for where and order should be brokered to. For reference this scenario can be used for routing glasses based on optic type.

https://docs.hotwax.co/krewe/flows/brokering/rxnashville

When the user selects a product they should also have the ability to broke the entire order or just that item. Something like:

Orders where this product exists
Order items for this product

**Comment by dixitdeepak** [comment]
This has been done, Added `OIP_PROD_CATEGORY` enumeration id to set the order filter condition based on product category. 

If productCategtoryId is configured as OrderFilterCondition, It will check the product category member for specified condition. 


```    <org.apache.ofbiz.common.enum.Enumeration enumId="OIP_PROD_CATEGORY" description="Product category" sequenceNum="35" enumTypeId="ORD_FILTER_PRM_TYPE" enumCode="productCategoryId"/>
```
